baseURL = "https://evankerrickford/"
languageCode = "en-us"
theme = "pitchdeck"
title = "Pitchdeck"
[Author]
name = "EKF"
[[menu.main]]
name = "View on Github"
url = "https://github.com/evankford/pitchdecktheme"
weight = 10
[params]
logo = "/logo.svg "
